set path_symbol_data_drive "Δ "
set path_symbol_os_drive "○ "
set path_symbol_projects_dir "◻ "
set path_symbol_archived_projects_dir "≡ "
set path_symbol_resources_dir "∷ "
set path_symbol_music_projects_dir "≺ "
set path_symbol_windows_home "≈ "
